source 'https://rubygems.org'

gem 'rails', '3.2.1'
gem 'mail_friday', :path => '/home/kill/code/mail_friday'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'






# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
